services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: notesai

    ports:
      - "5432:5432"

  backend:
    build:
      context: .

    container_name: backend

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - kafka
      - postgres

  ocr_consumer:
    build:
      context: .

    container_name: ocr_consumer

    command: python -m app.kafka.consumer.ocr_consumer

    environment:
      PYTHONUNBUFFERED: 1
      WS_NOTIFY_URL: http://backend:8000/internal/ws/notify

    env_file:
      - .env

  ai_consumer:
    build:
      context: .

    container_name: ai_consumer

    command: python -m app.kafka.consumer.ai_formatter_consumer

    environment:
      PYTHONUNBUFFERED: 1
      WS_NOTIFY_URL: http://backend:8000/internal/ws/notify

    env_file:
      - .env

    depends_on:
      - kafka
      - postgres

  pdf_consumer:
    build:
      context: .

    container_name: pdf_consumer

    command: python -m app.kafka.consumer.pdf_consumer

    environment:
      PYTHONUNBUFFERED: 1
      WS_NOTIFY_URL: http://backend:8000/internal/ws/notify

    env_file:
      - .env

    depends_on:
      - kafka
      - postgres
