"""fix note status correctly

Revision ID: 26e9cec5eddf
Revises: c9901218322a
Create Date: 2026-05-23 01:53:38.123721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e9cec5eddf'
down_revision: Union[str, Sequence[str], None] = 'c9901218322a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('original_file_url', sa.String(), nullable=False),
    sa.Column('generated_pdf_url', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'OCR_PROCESSING', 'OCR_COMPLETED', 'AI_PROCESSING', 'PDF_GENERATING', 'COMPLETED', 'FAILED', name='note_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
